<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="ContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TestDB.mdf;Integrated Security=True" SettingsObjectName="TestTask.Properties.Settings" SettingsPropertyName="TestDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vanzari" Member="Vanzari">
    <Type Name="Vanzari">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denumire" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pret" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cantitate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>